#!/bin/sh
#set -x

TOOL_NAME="Microsoft Outlook Web Add-in Promotion"
TOOL_VERSION="1.0"

## Copyright (c) 2020 Microsoft Corp. All rights reserved.
## Scripts are not supported under any Microsoft standard support program or service. The scripts are provided AS IS without warranty of any kind.
## Microsoft disclaims all implied warranties including, without limitation, any implied warranties of merchantability or of fitness for a 
## particular purpose. The entire risk arising out of the use or performance of the scripts and documentation remains with you. In no event shall
## Microsoft, its authors, or anyone else involved in the creation, production, or delivery of the scripts be liable for any damages whatsoever 
## (including, without limitation, damages for loss of business profits, business interruption, loss of business information, or other pecuniary 
## loss) arising out of the use of or inability to use the sample scripts or documentation, even if Microsoft has been advised of the possibility
## of such damages.
## Feedback: pbowden@microsoft.com

# This script tells New Outlook to promote WebEx and Zoom add-ins to the New Event toolbar if they are present.
# This aids with feature discoverability, especially for users who are moving from classic Outlook with a plug-in to New Outlook with a web add-in.
# The script sets the default state for the toolbar, but still allows users to customize it.
# This script should be run on each Mac, ideally through a management agent.

sudo defaults write /Library/Preferences/com.microsoft.Outlook ToolbarCustomization_CalendarEventEditorToolView_Preference -array freeBusy togglePrivateEvent attendeeOptions showScheduleAssistant attach a7ca6c74-33fb-43a4-a3e4-781078f0eff5-msgReadGroup 7a91e319-a65d-4ceb-909b-12203561dbf5-apptOrganizerCommandGroup


exit 0
